// <auto-generated />
namespace REM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddSetterToBookingCreatedAt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSetterToBookingCreatedAt));
        
        string IMigrationMetadata.Id
        {
            get { return "201905300932324_AddSetterToBookingCreatedAt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
